name: Node.js CI
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Perform a coverage test
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run cov
      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
